### PR TITLE
Inform Terraform if Cluster resource has been removed

### LINKED ISSUE #28: External cluster deletion not handled gracefully
Thanks for this module, its great!

I had a cluster that I've deleted in the in UI and the module doesn't seem to handle it gracefully:

```
Error reading MongoDB Cluster integration: MongoDB Atlas: 404 No cluster with ID integration exists in group <GROUPID>.
```

### PR DESCRIPTION
**Pull request by v00d00**
Fixes #28

### CODE REVIEW

**Comment by v00d00** [comment]
Any news?

**Comment by v00d00** [comment]
Usually the provider notices the resource has gone and creates you a new one, that's the behaviour of the AWS provider at least.

**Comment by mmindenhall** [comment]
@akshaykarle, yes, I think all of the resources should behave this way.  I just ran into this issue with a DB user that we had deleted, and found the provider didn't just re-create it.

**Comment by akshaykarle** [comment]
Okay, so i will merge @v00d00 it in, but let's also do it for the other resources.

**Pull request merged**
