### PR TITLE
Support for provider backups in mongodbatlas_cluster

### PR DESCRIPTION
**Pull request by dpiddockcmp**
Requires https://github.com/akshaykarle/go-mongodbatlas/pull/5 and a `vendor` update.

### CODE REVIEW

**Comment by akshaykarle** [comment]
Hello @dpiddockcmp, thank you for the PRs. I've merged in https://github.com/akshaykarle/go-mongodbatlas/pull/5, so if you run `make vendor-fetch` should update the dependency and we can merge it in?

**Comment by dpiddockcmp** [comment]
Done. 

Had some trouble with govendor: `Different Canonical Packages for github.com/dghubble/sling` which I "solved" by deleting the `vendor/github.com/dghubble/` folder.

**Comment by akshaykarle** [comment]
Perfect! Thanks for the PR @dpiddockcmp :)

**Comment by dpiddockcmp** [comment]
Hi @akshaykarle. Could you create a point release with this PR included? Thank you :)

**Pull request merged**
